# Generated by Django 5.2.7 on 2025-10-26 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtransfer',
            name='executed',
        ),
        migrations.RemoveField(
            model_name='scheduledtransfer',
            name='txn',
        ),
        migrations.AddField(
            model_name='scheduledtransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledtransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledtransfer',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtransfer',
            name='from_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_from', to='core.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledtransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduledtransfer',
            name='to_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_to', to='core.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledtransfer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
